name: check

on:
  push:
    branches-ignore: [main]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: pnpm run build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: docs/.vitepress/dist
          retention-days: 7

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: lint-md
        run: pnpm exec lint-md docs/**

      - name: markdownlint
        if: failure() || success()
        run: pnpm exec markdownlint-cli2
